services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=fernando
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
    driver: local